# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      CODECOV_TOKEN: de07e353-a554-4000-82a9-650da0f051a1
    steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    
    # Build the project
    - run: 
        name: Build the project
        command: mvn package dependency:go-offline
    
    # Download and install GHR
    - run:
        name: Download and Install GitHub Release Tool (ghr)
        command: |
          wget -c https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz
          tar -xvzf ghr_v0.12.0_linux_amd64.tar.gz
    
    - run:
        name: Release to Github
        command: |
          VERSION=1.0.${CIRCLE_BUILD_NUM}
          ./ghr_v0.12.0_linux_amd64/ghr -t ${GITHUB_PERSONAL_TOKEN} -u hjchanna -r talend-validation-toolkit -c ${CIRCLE_SHA1} -delete ${VERSION} ./talend-validation-tool/target/talend-validation-tool.jar
    
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn clean install
    - run: mvn cobertura:cobertura
    - run: bash <(curl -s https://codecov.io/bash)